# Generated by Django 3.1.7 on 2021-03-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.publisher'),
        ),
    ]
